### ISSUE TITLE
Implement Jenkins automated testing during commit / tests / deployment

### ISSUE THREAD

**Issue by stikstof** [rivm-syso/OPS#11] opened 2020-03-06 21:43 UTC
#tbc

**Comment by RIVM-OPS** [comment] 2022-01-25 14:13
First of all, we'd like to apologise for the late reaction. We'll try to reply more quickly to future issues.
This issue is a duplicate of #9, therefore this issue will be closed and further comments are added to #9.

**Closed as completed by RIVM-OPS** 2022-01-25 14:13 UTC
